# -*- coding: utf-8 -*-
"""Python_Class_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsAIbx9MO2mBuakbwpGEOx741ZQ35PKK

# Python Coding Platform
* Google Colab (Online)
* Anaconda Full version (Offline)
* IDE: VSCode, PyCharm, Spyder, Jupyter notebook

# What is google colab?

*   Colaboratory, or “Colab” for short, is a product from Google Research. Colab allows anybody to write and execute arbitrary python code through the browser, and is especially well suited to machine learning, data analysis and education. More technically, Colab is a hosted Jupyter notebook service that requires no setup to use, while providing free access to computing resources including GPUs.
*  [Google Colab Setup](https://www.youtube.com/watch?v=RTOOo39iaSU&fbclid=IwAR3d4ONzNXsfRxGVOF0VQhiwhwnk4pfcKRTTHt5GXmwKJNSO-Xr180HZ7Pkhttps://)

# Variable

*   dynamically typed (C variables are statically typed)
*   do not need explicit declaration
* declaration happens automatically when you assign a value to a variable
"""

a = 'hello world'
print(a, type(a))
a = "hello world"
print(a)

a = 5
b = 10

a, b = 5, 10

print(a, 'apples')
# formatted print; similar to printf(f"{a} apples");
print(f"{a} apples")

print(f"{a} apples, {b} oranges") # 5 apples, 10 oranges
print("%2d apples, %2d oranges" % (a, b))

print(a, 'apples', b, 'oranges')

a = 3.5
a = a + 1 # 4.5
a = a - 2 # 2.5
a = a * 2 # 5
a = a / 2 # 2.5
a = a ** 2 # 2.5^2=6.25
a = a % 5 # 1.25 # modulus
print(a)

b = 3 ** 5 # 3^5
b = 6 % 4 # 2
print(b)

s = 'hello'
s = s + 'UIU'
print(s) # 'helloUIU'
s = s * 3
print(s) # 'helloUIUhelloUIUhelloUIU'

"""## Typecast"""

a = '12343'
print(type(a)) # <class 'str'>

a = int(a)
print(a, type(a)) # <class 'int'>

a = str(100)
print(a+a)

a = 'fariha'
x = 500
s = a + str(x)
print(s)

"""## Take input


*   python input is string unless you typecast


"""

a = int(input())
print(a, type(a))
print(a**2)

x = input('Enter your name ')
print('you entered', x)

n = input()
print('input is', n)
n = n * 2
print('input * 2 is', n)

n = float(input('Enter a number: '))
print('input is', n)
n = n * 2
print('input * 2 is', n)

"""# If Else


*   if
*   elif
*   else
*   NO CURLY BRACES. **INDENTATION MATTERS.**



"""

a, b = 12, 33
if (a < b):
      print('hello')
      if a < 10:
        print( a, ' is less than 10')

# a = 2
# b = 5
a, b = 20, 5
if a > b:
    print('a is greater than b') # yes
    if a < 10:
        print('a is less than 10') # no
    elif a < 100: # else if
        print('a is greater than 9 and less than 100') # yes
else:
    print('a is not greater than b') # no

a = 23
b = 2456632412434312513343
if a > b:
    print(a, 'is greater than', b)
elif a == b:
    print(a, 'is equal to', b)
else:
    print(a, 'is less than', b)

"""# [Operators](https://www.w3schools.com/python/python_operators.asp)"""

a = 2
if a > 1 and a <= 10: # yes
    print('1 < a <= 10')
if a == 2 or a >= 1: # yes
    print('a is greater than or equal to 1')
if a == 2: # yes
    print('a is 2')
if a != 2: # no
    print('a is not 2')

if a is 2: # yes
    print('a is 2')
if a is not 4: # yes
    print('a is not 4')

"""# [For loop](https://www.w3schools.com/python/python_for_loops.asp)"""

# for (int i=0; i<10; i++)
for i in range(10):
    print(i)

for i in range(0, 10, 2):
    print(i)

for i in range(0, 8, 2):
    print(i)

for i in range(1, 11): # 0 <= i <3
    print(i)

for i in range(0, 10):
    if i==3: break
    print(i)
print('reached end')

# 3, 7, 11, 15, 19
for i in range(3, 20, 4):
    print(i)

for i in range(0, 10, 3): # start, end, stepsize
    print(i)

"""# While loop"""

n = 5/2
print(n)

n = 0
while True:
    print(n)
    # n++, n--, --n, ++n is not supported
    n += 1
    n = n+1
    n = n-1
    n -= 1
    n *= 2
    n /= 2
    n += 1
    if n == 5: break

i = 1
while i < 6:
    print(i)
    i += 2

i = 1
while i < 100:
    if i % 10 == 0:
        print(i)
    elif i % 23 == 0:
        print(i, 'need to break')
        break
    i += 3

a = (4,5,6)
print(type(a))

print(a[0])

"""# [List](https://www.w3schools.com/python/python_lists.asp)


*   Heterogenous
*   Multiple data type can be present in a single list


"""

arr = ['apple', 'grape', 100, 3.4, [1, 2] , (2, 3)]
print(arr)

"""## indexing"""

print(arr[0])
print(arr[4], arr[4][0], arr[4][1])

"""## insert"""

arr.append('orange') # inserts at the last
print(arr)

arr.insert(1, 560)
print(arr)

"""## delete"""

print(arr.pop(2)) # delete from index
print(arr)

arr = [1,2,3,4,'orange', 'apple', 'orange']
arr.remove(4)
print(arr)

"""## search"""

if 'grape' in arr:
    print('found grape')
if 'orange' not in arr:
    print('orange not found')

"""## iterating a list"""

print(len(arr))

"""### way1"""

for item in arr:
    print(item)

"""### way2"""

for i in range(0, len(arr)):
    print(arr[i])

arr =  []
for i in range(2, 30, 2):
    arr.append(i)
print(arr)

"""## slicing"""

arr = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

temp = arr[1:5]
print(temp)

temp = arr[::-1]
print(temp)

print(arr)

temp = arr[3:7] # 8 10 12 14
temp = temp[1:3] # 10 12
print(temp)

temp = arr[:4+1]
print(temp)

temp = arr[5:]
print(temp)

print(arr * 3)
print(arr + arr)

a = []
for i in range(0, 5):
    x = int(input())
    a.append(x)


print(a)

"""## copy a list"""

foo = [1, 2, 3]
bar = foo
bar.append(4)
print(foo, bar, '\n')

foo = [1, 2, 3]
bar = foo.copy()
bar.append(5)
print(foo, bar, '\n')

foo = [1, 2, []]
bar = foo
bar[-1].append(4)
print(foo, bar, '\n')

foo = [1, 2, []]
bar = foo.copy()
bar[-1].append(5)
print(foo, bar, '\n')

import copy
foo = [1, 2, []]
bar = copy.deepcopy(foo)
bar[-1].append(5)
print(foo, bar, '\n')

"""# Practice problem 1"""

## print all pair of numbers from a list

l = [1, 2, 3, 4, 5]

for i in range(len(l)):
    for j in range(i+1, len(l)):
        print(l[i], l[j])

"""# Dictionary"""

dictionary = {
    "name" : "osama",
    "email" : "osama@cse.uiu.ac.bd",
    "joined" : 2024,
    "id" :    12,
    45: 'a',
    (1,2,3) : [2,3]
}
dictionary

dictionary["name"]

d = {
    "name" : "fariha",
    "email" : 'fariha@cse.uiu.ac.bd',
    "position" : "lecturer",
    "joined" : 2019,
    2 : "???",
    3 : 234,
    3 : 12345,
    1 : "what",
    list : [1,3, "blue"]
}

d[1]

# print(d)
#print(d.keys())
print(d.values())

"""## get"""

print(d.get('joined'))
print(d['joined'])
print("fariha" in d)

"""## iterate"""

for i in d:
    print(i, " --- ", d[i])

"""## change value, delete key-value pair"""

d['name'] = 'AHMOH'
d['joined'] = '2020'
print(d)

for x in d:
    print(x, ':', d[x])

"""# Practice problem 2"""

sentence = "I study in UIU"
sentence.count("I")

## write a code that counts the frequency of each letter in a sentence

sentence = "I study in UIU"

freq = {}
print(type(freq))

for i in range(len(sentence)):
    # print(sentence[i])
    char = sentence[i]
    if char not in freq:
        freq[char] = 0
    freq[char] = freq[char]+1

for char in freq:
    print(f"{char}: {freq[char]}")

print(freq)

"""# Function"""

# int sum(int a, int b){
#     return a + b;
# }

def sum(a, b):
    return a, b, a + b

p, q, r = sum("s","e")
print(p, q, r)

def hello(name):
    name = name.capitalize()
    print('Hello',name)

hello('fariha')

# hello(1) # error

def test(arr):
  return (arr + arr)

print(test([1,2,4,6,7]))
print(test(100))
print(test("good"))

def minmax(arr):
  return min(arr), max(arr)

listt = [1, 0, 9, 8, -1]
min_, max_ = minmax(listt)
print(f'min: {min_}, max: {max_}')

a = minmax(listt)
print(a[0], a[1])

def canvote(age=0):
    if age >= 18:
        print("can vote at the age", age)
        return True
    else:
        print("can't vote at the age", age)
        return False

print(canvote(132), '\n')
print(canvote(age=31), '\n')
print(canvote(), '\n')

def canvote(is_citizen, age=0):
    if not is_citizen:
        print("can't vote", age)
        return False
    if age >= 18:
        print("can vote at the age", age)
        return True
    else:
        print("can't vote at the age", age)
        return False

print(canvote(True, 132), '\n')
print(canvote(False, age=31), '\n')
print(canvote(), '\n') # error: missing 1 argument
# print(canvote(is_citizen=False, 31), '\n') # error: positional argument follows keyword argument

"""# Practice problem 3"""

# calculate the distance between two points
import math

def distance(x1, y1, x2, y2):
    return math.sqrt((x1-x2)**2+(y1-y2)**2)

distance(1, 1, 4, 5)

"""# Class in python"""

print('Hello')

class Employee:
  emp_num = 0 # works like static variable common to all objects of a class

  def __init__(self, first, last, pay): # constructor
    self.first = first # member variable
    self.last = last # member variable
    self.email = first + '.' + last + '@email.com' # member variable
    self.pay = pay # member variable
    apple = 1 # not member variable
    Employee.emp_num += 1 # static variable

  def fullname(self): # self is comparable to this keyword of Java
    return f'{self.first} {self.last}'# "%s %s", self.first, self.last

  def applyRaise(self, raise_):
    self.pay = int(self.pay * raise_)

  def __str__(self): # toString()
    return f'{self.fullname()} - {self.email}: {self.pay}'

  @staticmethod # (Decorator) same working procedure for all objects of a class
  def is_holiday(day):
    holidays = [1, 30, 49, 350]
    if day in holidays:
        return True
    else:
      return False

print(Employee.emp_num) # 0

emp_1 = Employee('Corey', 'Schafer', 50000)
emp_2 = Employee('Test', 'Employee', 60000)


print(Employee.emp_num) # 2

emp_2 = Employee('Test', 'Employee33', 60000)

print(Employee.emp_num) # 3


print(emp_1.fullname()) # Corey Schafer

emp_1.applyRaise(1.5)
print(emp_1.pay) # 75000

print(Employee.is_holiday(30)) # True
print(Employee.is_holiday(31)) # False

print(emp_1) # Corey Schafer corey.schafer@gmail.com 75000

class Employee:
  emp_num = 0
  def __init__(self, first, last, pay):
    self.first = first
    self.last = last
    self.email = first + '.' + last + '@email.com'
    self.pay = pay
    Employee.emp_num += 1

  def fullname(self):
    return f'{self.first} {self.last}'

  def applyRaise(self,raise_):
    self.pay = int(self.pay * raise_)


class Developer(Employee):
    def __init__(self, first, last, pay, prog_lang):
        super().__init__(first, last, pay) # call parent class constructor
        self.prog_lang = prog_lang


class Manager(Employee):
  def __init__(self, first, last, pay, employees=None):
      super().__init__(first, last, pay)
      if employees is None:
          self.employees = []
      else:
          self.employees = employees

  def add_emp(self, emp):
      if emp not in self.employees:
          self.employees.append(emp)

  def remove_emp(self, emp):
      if emp in self.employees:
          self.employees.remove(emp)

  def print_emps(self):
      for emp in self.employees:
          print('-->', emp.fullname())

dev_1 = Developer('Corey', 'Schafer', 50000, 'Python')
dev_2 = Developer('Test', 'Employee', 60000, 'Java')

mgr_1 = Manager('Sue', 'Smith', 90000, [dev_1])
print(mgr_1.email)

mgr_1.add_emp(dev_2)
mgr_1.print_emps()
print()

mgr_1.remove_emp(dev_2)
mgr_1.print_emps()
print()

print(isinstance(mgr_1, Manager))  # Is mgr_1 an instance of Manager?
print(isinstance(mgr_1, Employee))
print(isinstance(mgr_1, Developer))
print()

print(issubclass(Developer, Employee)) # Is Developer class a subclass of Employee class??

print('hi')
def main():
    print('hello world')

if __name__=='__main__':
    main()

"""## Does Python support function overloading?
Python does not support function overloading. When we define multiple functions with the same name, the later one always overrides the prior and thus, in the namespace, there will always be a single entry against each function name

* https://www.geeksforgeeks.org/python-method-overloading/

# Practice problem 4
"""

# write a class Point to store the x,y coords of 2D points.
# The class should have the methods move_left, move_right, move_up, move down.
# move_left moves the point 1 cell to the left, move_right moves the point 1 cell to the right
# move_up moves the point 1 cell up, and move_down moves the point 1 cell down
# write a distance function to calculate the manhattan distance between two points

class Point:

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def move_left(self):
        self.x += 1

    def move_right(self):
        self.x -= 1

    def move_up(self):
        self.y += 1

    def move_down(self):
        self.y -= 1

    def distance(self, p):
        return Point.euclid_dist(self, p)

    @staticmethod
    def euclid_dist(p1, p2):
        return ((p1.x-p2.x)**2+(p1.y-p2.y)**2) ** 0.5

p1 = Point(2, 4)
p2 = Point(0, 0)
print('distance %.2f'%Point.euclid_dist(p1,p2))

p2.move_down()
print('distance %.2f'%Point.euclid_dist(p1,p2))

"""# Numpy array


* stores and manipulates n-dimensional arrays
* stores values of same type


"""

# numpy tutorial - http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays
# numpy uses the facility of GPU. So, try to use it instead of for loop
import numpy as np

a = [3, 6, 7]
print(type(a))

import numpy as np
arr = np.array(a)
print(type(arr))

print(arr.shape)
print(arr)

a = [
     [1, 4],
     [3, 5]
]
a = np.array(a)
print(a)
print(a.shape)

print(a[1, 1])

a = np.array([3, 5, 4])
print(type(a))
print(a.shape)
print(a[0])
print(a[10]) # index out of bound

b = np.array([
              [1,2,3,2],
              [4,5,6,2],
              [4,5,6,2],
              [4,5,6,2]
              ])
print(b.shape)
print(b[0][0], b[0, 1], b[1, 0])

a = np.random.random((4, 5))
print(a)

a = np.random.randint(0, 50, (4, 5))
# a = np.random.randint(low=0, high=10, size=(4, 5))
print(a)

# a = [
#      []
#      []
#      []
# ]

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((2,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 5)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

import numpy as np

d = np.eye(3)
d

(d+3)*100

d = np.eye(3)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

a = np.random.random((3,4))
print(a)
a = np.random.randint(0,10,(3,4))
print(a)

"""## slicing"""

a = np.array([
              [1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 0, 1, 2]
              ])

a[:, :]

print(a[1:3,:], '\n')
print(a[1:3,2:], '\n')
print(a[1:3,2:3], '\n')

"""## datatype"""

# you can explicitly specify data type
# basic data types https://numpy.org/doc/stable/user/basics.types.html
x = np.array([[1,2],[3,4]], dtype=np.float32)
y = np.array([[5,6],[7,8]], dtype=np.float64)

a = np.array()
print(a)

# input 2d array of shape (3,4)

arr = []

for i in range(3):
  arr.append([])
  for  j in range(4):
    x = int(input())
    arr[i].append(x)

arr

2# input 3D array
arr = []
for k in range(0,1):
  arr.append([])
  for i in range(0,3):
      arr[k].append([])
      for j in range(0,3):
          x = int(input())
          arr[k][i].append(x)


arr
#arr = np.array(arr)
#print('\n', arr)

arr = np.array(arr)
arr.shape

"""2## operations: add, mult, div etc."""

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y)
print(x - y)
print(np.add(x, y)) #time complexity O(1) if we use GPU

print( x+100 )
print((x+100) / 2)

z= x/y
print(z)

z = x*y # element wise multiplication
print(z)

print(x.dot(y)) # matrix multiplication / dot product
print(np.dot(x, y))

# https://www.mathsisfun.com/algebra/matrix-multiplying.html  -> matrix dot product

x = np.array([
              [1,2,5],
              [3,4,1]
              ])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[8 8]"

import numpy as np
x = np.array([
                [
                    [1,2,5],
                    [3,4,6]
                ],[
                    [7,8,9],
                    [10,11,12]
                ]
            ]
              )
print(x.shape)
print(x[0,1,2])
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
print(np.sum(x, axis=2))

# print(np.sum(x, axis=0))
# shape is
x = np.array([
                [
                    [1,2,5],
                    [3,4,6]
                ],[
                    [7,8,9],
                    [10,11,12]
                ]
            ])

x[0, 1, 1], x[1, 1, 1]

print(x.shape)

# (i, j, k) = (2, 2, 3)
for j in range(0, 2):
    for k in range(0, 3):
        sum = 0
        for i in range(0, 2):
            sum += x[i, j, k]
        print(sum, end=' ')
    print()

x = np.array([
              [1,2,5],
              [3,4,1]
              ])
print(x)

# matrix transpose
print(x.T)

print(np.sqrt(x))

# conversion
a = [[1,2,3],[4,5,6]]
print(type(a))

a= np.array(a)
print(type(a))

a= a.tolist()
print(a)
print(type(a))

a = [[1,2,3],[4,5,6]]
print(a)
b = a # copy by reference
# b = a.copy() # copy by value
b[0] = 999
print(a)

"""## reshape"""

# 2d array
a = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
a.shape

b = np.reshape(a, (1,1,2,6))
b

culprit1 = np.reshape(a, (1,1,1,1,12))
culprit1

v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# print(v * w) # can't do this, need to reshape

v = np.reshape(v, (3, 1))
v

print(v * w)

v = np.array([
              [1,2,3],
              [4,5,6]
              ])
w = np.array([[6,7]])
print(v.shape, w.shape)
# print(v.dot(w)) # can't do this

v = np.reshape(w, (2, 1))
print(v.shape)

print(v.dot(w))

y = np.array([
              [1,2,3],
              [4,5,6]
              ])
# print(y.dot(w)) # can't do this
print(y.shape, w.shape)
print(y.T.dot(w.T))

"""# matplotlib"""

import numpy as np
import matplotlib.pyplot as plt
import math

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.001) # [0, 0.1, 0.2, 0.3, ... 3*3.1416]#
y1 = np.sin(x)
y2 = np.cos(x)
y = 2*x

print(x)
print(y1)

plt.plot(x, y1, 'r')
plt.plot(x, y2, 'b')
plt.plot(x,y, 'g')
plt.show()  # You must call plt.show() to make graphics appear

x = np.arange(0, 2, 0.5)
print(x)
y = 2 * x
print(y)

import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
y_tan = np.tan(x)

# Plot the points using matplotlib
plt.plot(x, y_sin, color='red')
plt.plot(x, y_cos, 'blue')
plt.plot(x, y_tan, 'green')
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine', "tan hello"])
plt.show()

"""# Priority Queue"""

A = [
     ['S', 10],
     ['A', 12],
     ['G', 0]
]